package org.example.Models.Enums;

public enum TileType {
    WALL,SHACK,LAKE,TREE,GREENHOUSE,QUARRY,EMPTY,BLACKSMITH,JOJAMART,GENERALSTORE,CARPENTERSHOP,
    FISHSHOP,RANCH,STARDROPSALOON,PLAYER,ROCK,FORAGING,FERTILE,SHIPPINGBIN,BUILDING,ANIMAL,
    SEBASTIAN_HOUSE,
    ABIGAIL_HOUSE,
    HARVEY_HOUSE,
    LEAH_HOUSE,
    ROBIN_HOUSE,
    SEBASTIAN_NPC, ABIGAIL_NPC, HARVEY_NPC, LEAH_NPC, ROBIN_NPC;
}
