package org.example.Models.Enums;

public enum ItemSubType {
    //Tools
    HOE, PICKAXE, AXE, WATERINGCAN, FISHINGPOLE, SCYTHE,SHEAR,TRASH_CAN,MILKPAIL,

    //Foods
    FRUIT,SYRUP,FISH,TRUFFLE,EGG,MILK,

    //animal
    CHICKEN,DUCK,RABBIT,DINOSAUR,COW,GOAT,SHEEP,PIG,

    //building
    COOP,BARN,

    //Materials
    SEED,WOOD,IRON,COOPER,GOLD,COAL,UNKNOWN,BAIT,
    QUARTZ,EARTHCRYSTAL,FROZENTEAR,FIREQUARTZ,EMERALD,AQUAMARINE,RUBY,AMETHYST
    ,TOPAZ,JADE,DIAMOND,PRISMATICSHARD,IRIDUIM,FERTILIZER,STONE,FIBER,HAY,FURR;

}
