package org.example.Models.Enums;

public enum TileType {
    WALL,SHACK,LAKE,TREE,GREENHOUSE,QUARRY,EMPTY,BLACKSMITH,JOJAMART,GENERALSTORE,CARPERNTERSHOP,
    FISHSHOP,RANCH,STARDROPSALOON,PLAYER;
}
