package org.example.Models.Enums;

public enum TileType {
    WALL,SHACK,LAKE,TREE,GREENHOUSE,QUARRY,EMPTY,BLACKSMITH,JOJAMART,GENERALSTORE,CARPENTERSHOP,
    FISHSHOP,RANCH,STARDROPSALOON,PLAYER,ROCK,FORAGING,FERTILE;
}
